###
# List of methods/modules and their dependencies:
###
modules:
    - name: array_ops
    - name: assoc_rules
    - name: conjugate_gradient
      depends: ['array_ops']
    - name: svd_mf
    - name: linalg
    - name: utilities
      depends: ['linalg']
    - name: regress
      depends: ['utilities', 'array_ops']
    - name: lda
      depends: ['array_ops']
    - name: kmeans
      depends: ['array_ops', 'sample']
    - name: sample
      depends: ['utilities']
    - name: tsa
    - name: convex
      depends: ['utilities']
    - name: pca
      depends: ['linalg', 'convex']
    - name: elastic_net
    - name: linear_systems
      depends: ['utilities']
    - name: sketch
    - name: summary
      depends: ['utilities', 'sketch']
    - name: stats

